// auto generated by posthog-react-native-session-replay

export declare type ReactNativeSessionReplayStatic = {
  start: (sessionId: string, endpoint: string) => Promise<void>
  startSession: (sessionId: string) => Promise<void>
  endSession: () => Promise<void>
  isEnabled: () => Promise<boolean>
}
