// auto generated by posthog-react-native-session-replay

import type { ReactNativeSessionReplayStatic } from './ReactNativeSessionReplayStatic';
declare const ReactNativeSessionReplay: ReactNativeSessionReplayStatic;
export default ReactNativeSessionReplay;
