name: Examples

on:
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version: 18

      - name: macos example
        run: |
            cd examples/example_rn_macos
            yarn global add yalc
            npm install --global rollup
            yarn install
            npx react-native-macos-init
            make install
            make build
